name: COOK4U CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x' 

    - name: Install Frontend Dependencies
      run: npm install

    - name: Build Frontend (Check lỗi cú pháp và đóng gói)
      run: npm run build

  build-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Backend Dependencies
      working-directory: ./backend # Trỏ vào thư mục chứa backend
      run: npm install

    # - name: Run Backend Tests
    #   working-directory: ./backend
    #   run: npm test